apiVersion: apps/v1
kind: Deployment
metadata:
  name: marks-app-deploy
  labels:
    app: marks-app
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: marks-app
      
  template:
    metadata:
      labels:
        app: marks-app
    spec:
      containers:
        - name: marks-app
          image: sburla/hello:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
            name: hello

---
apiVersion: v1
kind: Service
metadata:
  name: marks-app-svc
  labels:
    app: marks-app
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: marks-app
  type: LoadBalancer

